### ISSUE TITLE
Issues in using the sw

### ISSUE THREAD

**Issue by alecive** [UbiquityRobotics/speech_commands#1]
Hello @jrlandau ,

this seems a very interesting software to use, but I am currently having some issues with following your `README.md` and testing the SW on my local Ubuntu 14.04 machine (before eventually deploying it on the robot). 
Let me explain my procedure:
1. I successfully Installed rosbridge, the apache2 web server, enabled the apache2 ssl module, configured apache2 for HTTPS, restarted the service.
2. I successfully tested the server from a browser, both with `http://172.27.199.36/index.html` and with `https://172.27.199.36/index.html`. It behaves as expected.
3. I copied the full content of this repo in `/var/www/html`
4. I copied `/etc/ssl/private/ssl-cert-snakeoil.key` to `/etc/ssl/certs/`. I made it readable. I modified the `rosbridge_websocket.launch` file. I installed `tf2_web_republisher`.
5. I launched the `rosbridge_server` and the `tf2_web_republisher` on my machine.
6. I tried to access `https://172.27.199.36/speechcommands.html` (HTTPS), but it still gives me an error, as if I was not using the ssl key.
7. If I instead access `http://172.27.199.36/speechcommands.html` (HTTP), I get on the page, but then I am not able to connect to the robot's URL

So my questions are two:
- How to fix problem 6? 
- For step 7, I tried the following:
  - `ws://127.0.0.1:9090`, `wss://127.0.0.1:9090`, `http://127.0.0.1:9090`, `https://127.0.0.1:9090` (localhost with the rosbridge websocket server port)
  - `ws://127.0.0.1:11311`, `wss://127.0.0.1:11311`, `http://127.0.0.1:11311`, `https://127.0.0.1:11311` (localhost with the ROS_MASTER_URI port).  In this case I don't hear the error message, though.
  - `ws://172.27.199.36/:9090`, `wss://172.27.199.36/:9090`, `http://172.27.199.36/:9090`, `https://172.27.199.36/:9090` (apache server's ip [and my IP] with the rosbridge websocket server port)
  - `ws://172.27.199.36/:11311`, `wss://172.27.199.36/:11311`, `http://172.27.199.36/:11311`, `https://172.27.199.36/:11311` (apache server's ip [and my IP] with the ROS_MASTER_URI port). In this case I don't hear the error message, though.

**Comment by alecive** [comment]
Is `bootbox.min.js` important? Because it seems to be required but it is missing from the repo. This is the console output while trying to connect to `ws://172.27.199.36:9090`:

```
GET http://172.27.199.36/scripts/bootbox.min.js 
speechcommands.html:362 GET http://172.27.199.36/scripts/bootbox.min.js 404 (Not Found)
roslib.min.js:1 WebSocket connection to 'ws://172.27.199.36:9090/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
speechcommands.html?url=http%3A%2F%2F127.0.0.1%3A9090:493 Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2…}
speechcommands.html?url=http%3A%2F%2F127.0.0.1%3A9090:499 Uncaught ReferenceError: bootbox is not defined(anonymous function) @ speechcommands.html?url=http%3A%2F%2F127.0.0.1%3A9090:499s.emit @ eventemitter2.min.js:1onerror @ roslib.min.js:1
```

This is instead the output of my `roslaunch rosbridge_server rosbridge_websocket.launch` (so that you can see the port names):

```
... logging to /home/alecive/.ros/log/fe11ca40-55a2-11e6-99d6-6c2995068b46/roslaunch-malakim-7516.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://malakim:45649/

SUMMARY
========

PARAMETERS
 * /rosbridge_websocket/address: 
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/certfile: /etc/ssl/certs/ss...
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/keyfile: /etc/ssl/certs/ss...
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)

auto-starting new master
process[master]: started with pid [7528]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to fe11ca40-55a2-11e6-99d6-6c2995068b46
process[rosout-1]: started with pid [7541]
started core service [/rosout]
process[rosbridge_websocket-2]: started with pid [7549]
process[rosapi-3]: started with pid [7553]
registered capabilities (classes):
 - rosbridge_library.capabilities.call_service.CallService
 - rosbridge_library.capabilities.advertise.Advertise
 - rosbridge_library.capabilities.publish.Publish
 - rosbridge_library.capabilities.subscribe.Subscribe
 - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
 - rosbridge_library.capabilities.advertise_service.AdvertiseService
 - rosbridge_library.capabilities.service_response.ServiceResponse
 - rosbridge_library.capabilities.unadvertise_service.UnadvertiseService
[INFO][/rosbridge_websocket::<module>]: Rosbridge WebSocket server started on port 9090
```

**Comment by anfederman** [comment]
On chrome, it will object to running https://  and a pop up will appear asking you to allow ssh.  Click advanced and then allow.
You should be allowed to click on the connect link and have it turn green.  You then should be able to move the robot if you have a robot base running and cmd_vel topics are being published.

**Comment by jrlandau** [comment]
Hi Alessandro,

I agree with Alan, you will have to go thru the ssh warning by clicking
"advanced".  Chrome does this because it does not trust the snakeoil
certificate, which is a self-signed certificate.

Bootbox provides a better dialog box than the standard one.  I used it for
alerts and confirmations.  I see that I did not include the file bootbox.min.js
in the scripts folder. I have now updated the repo to include the file.

I hope this solves the problem; please let me know if it doesn't.

Joe Landau

Joe Landau

**Comment by alecive** [comment]
@anfederman @jrlandau the advice you gave me solved the issue. Thank you for the help!

I suggest you to add it to the `README.md`, because not everyone might know how to tackle this issue.

**Comment by jrlandau** [comment]
Thanks for the suggestion.  Done.
