### ISSUE TITLE
Relative Distance should work without localization

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/speech_commands#11]
Definition of Done:

We can say "go 1 meter forward" without any localization system running, and the robot can do it.

**Comment by jim-v** [comment]
move_basic now handles relative goals (tested with rviz).  To close this issue, we need to verify that RobotCommander sends them.  They should be in the base_Link frame, and no tf is necessary

**Comment by jrlandau** [comment]
How would you like to proceed to verify this?

**Comment by jim-v** [comment]
@jrlandau, we could start by seeing if a goal is being sent.  On an Ubuntu machine (doesn't have to be a robot):
`roslaunch rosbridge_server rosbridge_websocket.launch`
and in another terminal:
`rostopic echo /move_base/goal`
Then, run RobotCommander, connect to server and send the forward 1 meter command.  If a goal is sent, then we are ready to test with `move_basic`.   If not, we should figure out why not.

**Comment by rohbotics** [comment]
What is the status of this issue?

**Comment by jrlandau** [comment]
Damned it I know.  It was working a few weeks ago, but does not seem to at
present.  I say "seem to" because I don't know if I am initializing the
robot correctly

**Comment by jrlandau** [comment]
Turns out that if I pkill roslaunch before setting up, then measured
movement works.  I think there had been an upgrade of 2-rosbridge installed
on that image, which I guess now deserves a second look.
